# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require a recent version of vagrant otherwise some have reported errors setting host names on boxes
Vagrant.require_version ">= 1.7.4"

# The number of minions to provision
$num_minion = 3

# ip configuration
$minion_ip_base = "10.246.2."
$minion_ips = $num_minion.times.collect { |n| $minion_ip_base + "#{n+2}" }
$minion_ips_str = $minion_ips.join(",")


# OS platform to box information
$boxes = {
  "centos" => {
    "name" => "centos/7",
  }
}
$box_os="centos"

# This stuff is cargo-culted from http://www.stefanwrobel.com/how-to-make-vagrant-performance-not-suck
# Give access to half of all cpu cores on the host. We divide by 2 as we assume
# that users are running with hyperthreads.
$vm_cpus = 1

# Give VM 512MB of RAM
$vm_mem = 1024

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  def customize_vm(config)
    config.vm.box = $boxes[$box_os]["name"]
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        sudo yum -yq install epel-release
        sudo yum update -yq
        curl -sSL https://get.docker.com/ | sh
        sudo usermod -aG docker $USER
        sudo systemctl restart docker
        sudo systemctl enable docker
        sudo yum install python-pip
        sudo pip install -U docker-compose
        curl -L https://github.com/docker/machine/releases/download/v0.7.0/docker-machine-`uname -s`-`uname -m` > ~/docker-machine
        sudo mv ~/docker-machine /usr/local/bin/docker-machine
        sudo chmod +x /usr/local/bin/docker-machine
    SHELL

    config.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", $vm_mem]
      v.customize ["modifyvm", :id, "--cpus", $vm_cpus]

      # Use faster paravirtualized networking
      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      v.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end


  # minion
  $num_minion.times do |n|
    minion_vm_name = "minion-#{n+1}"
    config.vm.define minion_vm_name do |minion|
      customize_vm minion

      minion_index = n+1
      minion_ip = $minion_ips[n]
      minion.vm.network "private_network", ip: "#{minion_ip}"
      minion.vm.hostname = "minion-#{minion_index}"
    end
  end

end
